adding stations between packages and tasks
xyng/yuoshi-backend-adapter pull request #14
Opened 2021-02-17 14:05 UTC by juliandierker

2021-02-18 07:01 UTC, xyng requested changes

2021-03-08 10:08 UTC, juliandierker commented on .prettierrc.json
> +	"printWidth": 120
huch, das sollte nicht mit in stage eigtl. darf es drin bleiben - nehme sonst raus

2021-03-09 07:17 UTC, xyng commented on .prettierrc.json
> +	"printWidth": 120
Passt. War nur etwas verwundert :-)

2021-03-09 07:19 UTC, xyng requested changes

2021-03-09 07:19 UTC, xyng commented on packages/backend-adapter-argonauts/src/adapters/StationAdapter.ts
> +	// getStation(station_id: string): Paginator<NSStationsAdapter.Station, any> {
Der Kommentar-Block kann vermutlich weg?

2021-03-09 07:19 UTC, xyng commented on packages/backend-adapter/src/adapters/AbstractStationsAdapter.ts
> +		// abstract getStation(station_id: string): AbstractPaginator<Station, any>
Auskommentierter Code. Kann das weg?

2021-04-06 10:18 UTC, merged